"""Packaged lookup tables: names, locations, experience curves, personal data.

Everything here is generated by tools/gen_data.py from the PKHeX resources and
loaded lazily, so importing the library does not pull ~2 MB of JSON into memory.
"""

from __future__ import annotations

import json
from functools import cache
from pathlib import Path

DATA_DIR = Path(__file__).parent

DEFAULT_LANGUAGE = "en"

# PKHeX LanguageID -> resource language code.
LANGUAGE_CODES = {
    1: "ja", 2: "en", 3: "fr", 4: "it", 5: "de",
    7: "es", 8: "ko", 9: "zh-Hans", 10: "zh-Hant",
}


def language_code(language_id: int) -> str:
    return LANGUAGE_CODES.get(language_id, DEFAULT_LANGUAGE)


@cache
def names(language: str = DEFAULT_LANGUAGE) -> dict[str, list[str]]:
    """All name lists for one language, keyed by list name."""
    path = DATA_DIR / "names" / f"{language}.json"
    if not path.exists():
        path = DATA_DIR / "names" / f"{DEFAULT_LANGUAGE}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def name_list(kind: str, language: str = DEFAULT_LANGUAGE) -> list[str]:
    return names(language).get(kind, [])


def lookup(kind: str, index: int, language: str = DEFAULT_LANGUAGE) -> str | None:
    """Name for ``index`` in list ``kind``, or None when out of range."""
    entries = name_list(kind, language)
    if 0 <= index < len(entries):
        return entries[index]
    return None


def item_name(index: int, generation: int, language: str = DEFAULT_LANGUAGE) -> str | None:
    """Item names diverge before Gen5; pick the list that matches the format.

    An index the era's own list does not have is unknown, not an item from a
    later game, so no fallback happens once a legacy list exists.
    """
    if 1 <= generation <= 4:
        legacy = name_list(f"items_gen{generation}", language)
        if legacy:
            return legacy[index] if 0 <= index < len(legacy) else None
    return lookup("items", index, language)


@cache
def locations(context: str) -> dict[str, dict[str, list[str]]]:
    """Met-location lists for one entity context, e.g. ``"gen9"``."""
    path = DATA_DIR / "locations" / f"{context}.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def location_name(
    context: str,
    game: str,
    index: int,
    language: str = DEFAULT_LANGUAGE,
) -> str | None:
    """Resolve a met-location index within its bank.

    Location ids are banked: 0-29999 come from the base list, and the 30000 /
    40000 / 60000 ranges each have their own list indexed from the bank start.
    """
    banks = locations(context).get(language) or locations(context).get(DEFAULT_LANGUAGE)
    if not banks:
        return None
    for start in (60000, 40000, 30000, 0):
        entries = banks.get(f"{game}:{start}")
        if entries is None or index < start:
            continue
        offset = index - start
        if offset < len(entries):
            return entries[offset] or None
        return None
    return None


@cache
def experience_tables() -> list[list[int]]:
    """Six growth-rate tables; ``table[growth][level - 1]`` is the EXP needed."""
    return json.loads((DATA_DIR / "experience.json").read_text())


@cache
def personal() -> dict[str, dict[str, list[int]]]:
    """Growth rate and gender ratio per species, per game table."""
    return json.loads((DATA_DIR / "personal.json").read_text())


def growth_rate(table: str, species: int) -> int:
    entry = personal().get(table)
    if entry and 0 <= species < len(entry["growth"]):
        return entry["growth"][species]
    return 0


def gender_ratio(table: str, species: int) -> int:
    entry = personal().get(table)
    if entry and 0 <= species < len(entry["gender"]):
        return entry["gender"][species]
    return 255
