#!/bin/sh
# Regenerate src/pkhexpy/strings/tables.py from the PKHeX reference source.
# Usage: sh tools/gen_tables.sh  (run from the repo root, with reference_PKHeX/ present)
set -e
S=reference_PKHeX/PKHeX.Core/PKM/Strings
OUT=src/pkhexpy/strings/tables.py

G12="--symbol NUL=0000 --symbol TOT=002A --symbol LPK=007B --symbol LMN=007D \
--symbol MNY=00A5 --symbol LPO=0040 --symbol LKE=0023 --symbol LEA=0025 \
--symbol DOT=2024 --symbol SPF=3000 --symbol SPH=0020 --symbol RET=23CE \
--symbol LAP=2019 --symbol NIS=32E5 --symbol NOS=32E8 \
--symbol LI0=FF10 --symbol LI1=FF11 --symbol LI2=FF12 --symbol LI3=FF13 \
--symbol LI4=FF14 --symbol LI5=FF15 --symbol LI6=FF16 --symbol LI7=FF17 \
--symbol LI8=FF18 --symbol LI9=FF19 --symbol LIA=FF21 --symbol LIB=FF22"

G3="--symbol Terminator=00FF --symbol HGM=246D --symbol HGF=246E \
--symbol FGM=2642 --symbol FGF=2640"

G4="--symbol NUL=FFFF --symbol EMP=FFFF --symbol HGM=246D --symbol HGF=246E"

KOR="--symbol NUL=0000 --symbol NULL=0000 --symbol RET=23CE"

emit() { python3 tools/extract_charmaps.py --source "$1" --table "$2" --pyname "$3" $4; echo; }

{
  echo '"""Character tables for Gen1-4 encodings.'
  echo
  echo 'Generated by tools/gen_tables.sh from the PKHeX reference source. Do not edit'
  echo 'by hand; regenerate instead. Entries equal to the terminator mark unused slots.'
  echo '"""'
  echo
  emit $S/StringConverter1.cs TableEN  G1_EN  "$G12"
  emit $S/StringConverter1.cs TableJP  G1_JP  "$G12"
  emit $S/StringConverter2.cs TableEN  G2_EN  "$G12"
  emit $S/StringConverter2.cs TableFRE G2_FRE "$G12"
  emit $S/StringConverter2.cs TableITA G2_ITA "$G12"
  emit $S/StringConverter2.cs TableJP  G2_JP  "$G12"
  emit $S/StringConverter3.cs G3_EN    G3_EN  "$G3"
  emit $S/StringConverter3.cs G3_JP    G3_JP  "$G3"
  emit $S/StringConverter4Util.cs TableINT G4_INT "$G4"
  emit $S/StringConverter4Util.cs TableKOR G4_KOR "$G4"
  emit $S/StringConverter7ZH.cs Table G7_ZH ""
  for t in 0 1 2 3 4 5 6 7 8 9 A B; do
    emit $S/StringConverter2KOR.cs "Table$t" "G2_KOR_$t" "$KOR"
  done
} > $OUT
python3 -c "import ast; ast.parse(open('$OUT').read())"
echo "wrote $OUT"
